server :
  context-path   : /api/v1

dataSource :
  driverClassName: org.postgresql.Driver
  url            : jdbc:postgresql://localhost:5432/inventory
  username       : postgres
  password       : 123456

hibernate :
  dialect      : org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto : none
